source 'http://rubygems.org'

# Bundle edge Rails instead:
# gem 'rails', :git => 'git://github.com/rails/rails.git'
gem 'rails', '3.1.1'

gem 'errship', :require => 'errship', :path => '../../'
gem 'airbrake'

gem 'sqlite3-ruby'
gem 'mongoid'
gem 'mongo_mapper'
gem 'bson_ext'
